// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCD-AxcBiJg7dgP0f5o5eVmXFJ3Ej0ZyXU',
    appId: '1:53023290243:web:68f10ac253caeb410c3cb6',
    messagingSenderId: '53023290243',
    projectId: 'ml-test-da447',
    authDomain: 'ml-test-da447.firebaseapp.com',
    storageBucket: 'ml-test-da447.appspot.com',
    measurementId: 'G-P9XJJXRP45',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBV7pK9p6yi4UsIozEElN_RuvNvFDcakFo',
    appId: '1:53023290243:android:c7a64612699999490c3cb6',
    messagingSenderId: '53023290243',
    projectId: 'ml-test-da447',
    storageBucket: 'ml-test-da447.appspot.com',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyALORQhR_MmKks-cZUnNbt_HsAp3yqWqi4',
    appId: '1:53023290243:ios:e702c0db8f1f65f00c3cb6',
    messagingSenderId: '53023290243',
    projectId: 'ml-test-da447',
    storageBucket: 'ml-test-da447.appspot.com',
    iosClientId: '53023290243-ecleutjp56jfk5fud130nq9uavfgibfi.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterFirebaseTemplate',
  );
}
